modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues_url}"

[[mods]]
modId="${mod_id}"
displayName="${mod_name}"
version="${mod_version}"
displayURL="${mod_display_url}"
authors="${mod_author}"
description="${mod_description}"
logoFile="${mod_logo}"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"